### ISSUE TITLE
adapting 10X scRNA 3' kit?

### ISSUE THREAD

**Issue by willey2020** [dbrg77/ISSAAC-seq#1]
Hello! Thank you for bringing this powerful method! 
I have a question if this method can be adapted in using 10X scRNA kit instead of scATAC kit, like the snare-seq strategy or adding poly T sequence on the oligo and then make it able to anneal to 3' RNA beads oligo? 
Thank you so much!!

**Comment by dbrg77** [comment]
Hi @willey2020 ,

Thanks for the comment. I think it is possible to do it with the 3' scRNA kit using the SNARE-seq like strategy by adding a splint oligo to capture the ATAC fragment to the dT containing beads. You need to do some testing on the reagents, the concentration and the amount of the oligo etc, which is a bit expensive for us to test.

The reason we chose the ATAC kit is we know that the first step is simple PCR, and we can use the reagents in the kit without any modification.

Hope this helps.

Xi

**Comment by willey2020** [comment]
Thank you so much Xi! This is very helpful!
